### PR TITLE
Introduce Jackson JQ Extension to Quarkiverse

### PR DESCRIPTION
**Pull request by ricardozanini**
Signed-off-by: Ricardo Zanini <zanini@redhat.com>

### CODE REVIEW

**Comment by aloubyansky** [comment]
@ricardozanini do you have the permissions to merge it? If you don't, let us know. It should be in your hands.

**Comment by ricardozanini** [comment]
@aloubyansky I sure have! I was just wondering if you guys don't want to take a look to make sure the guidelines were followed. For example, I've changed the groupId from `io.quarkiverse.quarkus-jackson-jq` to just `io.quarkiverse.jackson-jq`.

**Comment by aloubyansky** [comment]
>  I've changed the groupId from io.quarkiverse.quarkus-jackson-jq to just io.quarkiverse.jackson-jq

That's ok

**Review by aloubyansky — APPROVED** [review]
Looks good. You added a dependency on resteasy here, is it supposed to work also with resteasy-reactive?

**Comment by ricardozanini** [comment]
@aloubyansky many thanks! Oh no, the resteasy dependency is only for the integration tests. The main extension only requires `quarkus-jackson`. :)

**Comment by aloubyansky** [comment]
Right, sorry, that's good.

**Pull request merged**
