### PR TITLE
Update to jdk17

### PR DESCRIPTION
**Pull request by nmirasch**

### CODE REVIEW

**Comment by nmirasch** [comment]
@ricardozanini could you take a look?

**Comment by nmirasch** [comment]
@hbelmiro could you take a look?

**Review by ricardozanini — APPROVED** [review]
Great! Many thanks!

**Review by hbelmiro — COMMENTED** [review]
Why this is needed @nmirasch? If the idea is to drop support for Java 11, we should also update other GH Actions and the pom.xml.

**Comment by ricardozanini** [comment]
@hbelmiro we had a problem with Quarkus 3 integration branch. It seems fixed, but Quarkus is moving on, we should also. wdyt?

**Comment by nmirasch** [comment]
@hbelmiro my intention was just to fix the build, but maybe we need to change <maven.compiler.target> in pom.xml too. I think the Quarkus 3 integration also needs this jdk update to 17. Wdyt?

**Comment by hbelmiro** [comment]
That's totally fine for me to upgrade to 17. Just the intention of the PR that was not clear to me.

> @hbelmiro my intention was just to fix the build, but maybe we need to change <maven.compiler.target> in pom.xml too. I think the Quarkus 3 integration also needs this jdk update to 17. Wdyt?
> 
> And about "we should also update other GH Actions".. which ones? (I only find the ref in this two workflows)

Yeah, you're right @nmirasch. I thought there were more GH Actions to update, but there aren't. Just pom.xml.

**Review by hbelmiro — APPROVED** [review]

**Comment by hbelmiro** [comment]
@ricardozanini will we drop support to quarkus 2 here and in https://github.com/quarkiverse/quarkus-reactive-messaging-http too?

**Comment by ricardozanini** [comment]
> @ricardozanini will we drop support for quarkus 2 here and in https://github.com/quarkiverse/quarkus-reactive-messaging-http too?

Let's do it!

**Pull request merged**
